- name: writing down the general syntax of a ansible playbook
  hosts: web #targeted servers
  become: yes #indicates root user or not
  tasks: 
  - name: ping the server to test the connection
    ansible.builtin.ping:
    
  - name: install nginx on the node server
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run nginx
    ansibli.builtin.service:
      name: nginx
      state: started
              