- name: declaring variables in a file
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: " {{tournament}} is played by {{teams}} "

#make sure the file under vars_files have the same spelling as the one inthe repository
