#declaring the varialble at playbook level
- name: variable at playbook level
  hosts: localhost #it will automatically execute inthe ansible server, no need to mention it in the inventory
  become: yes
  vars: 
    person: "manoj"
    wishes: "good morning"
  tasks:
  - name: to  the play variables
    ansible.builtin.debug:
      msg: "hello {{person}} , a very {{wishes}}"

